version: '3'
services:
  freshrss:
    image: linuxserver/freshrss
    restart: unless-stopped
    environment:
      TZ: Europe/London
    volumes:
      - freshrss-config:/config
    depends_on:
      - freshrss-db
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.freshrss.loadbalancer.server.port=80"

      - "traefik.http.routers.freshrss-http.entrypoints=web"
      - "traefik.http.routers.freshrss-http.rule=Host(`news.$DOMAIN`)"
      - "traefik.http.routers.freshrss-http.middlewares=redirect-to-https"

      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.service=freshrss"
      - "traefik.http.routers.freshrss.rule=Host(`news.$DOMAIN`)"
      - "traefik.http.routers.freshrss.tls=true"
      - "traefik.http.routers.freshrss.tls.certresolver=resolver"

      - "traefik.http.routers.freshrss.middlewares=traefik-forward-auth"

  freshrss-db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: enable
      MYSQL_USER: ${FRESHRSS_DB_USER}
      MYSQL_PASSWORD: ${FRESHRSS_DB_PASSWORD}
      MYSQL_DATABASE: ${FRESHRSS_DB_DATABASE}
    volumes:
      - freshrss-db-data:/var/lib/mysql

volumes:
  freshrss-db-data:
  freshrss-config:
  