version: '3'
services:
  wiki:
    image: requarks/wiki:2
    restart: unless-stopped
    depends_on:
      - wiki-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_USER: $WIKIJS_DB_USER
      DB_PASS: $WIKIJS_DB_PASSWORD
      DB_NAME: $WIKIJS_DB_DATABASE
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.wiki.loadbalancer.server.port=3000"

      - "traefik.http.routers.wiki-http.entrypoints=web"
      - "traefik.http.routers.wiki-http.rule=Host(`wiki.$DOMAIN`)"
      - "traefik.http.routers.wiki-http.middlewares=redirect-to-https"

      - "traefik.http.routers.wiki.entrypoints=websecure"
      - "traefik.http.routers.wiki.service=wiki"
      - "traefik.http.routers.wiki.rule=Host(`wiki.$DOMAIN`)"
      - "traefik.http.routers.wiki.tls=true"
      - "traefik.http.routers.wiki.tls.certresolver=resolver"

      - "traefik.http.routers.wiki.middlewares=traefik-forward-auth"

  wiki-db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: $WIKIJS_DB_USER
      POSTGRES_PASSWORD: $WIKIJS_DB_PASSWORD
      POSTGRES_DB: $WIKIJS_DB_DATABASE
    restart: unless-stopped
    volumes:
      - wiki-db-data:/var/lib/postgresql/data

volumes:
  wiki-db-data: